### ISSUE TITLE
Only search suggestion ban detected when user also has search/thread ban

### ISSUE THREAD

**Issue by ghost** [shadowban-eu/TwitterShadowBanV2#22]
I've noticed quite often that the shadowban tester reports that a user only has a search suggestion ban, but it's obvious that they also have a search and a thread ban.

**Comment by rbeer** [comment]
Oh boy. 6 days without reply/acknowledgment. That's almost disrespectful. Sorry! :pensive: 
Good catch! Looks easy enough. Will test-drive and then merge, first thing in the morning.
