### ISSUE TITLE
Limited donation options

### ISSUE THREAD

**Issue by cb-tx** [shadowban-eu/TwitterShadowBanV2#25]
I was tweeting into the void like an idiot until I realized something was wrong. The other checkers I found online apparently don't work but I was able to get my ban lifted after confirming with your tool and telling twitter support how a gang of no debate ability having morons are abusing their report abuse function.

...Aaaanyway, I saw your your donate link and thought it would be nice to shoot a bit of appreciation for your time battling bs. I'm in the US and Paypal wants to charge me a dollar to buy you a beer 🙄 That's fine, I guess but I'd rather send btc than feed the monsters. No big deal, just a suggestion, if you're into that. Anyway, thanks. You can go ahead and close this if you want

**Comment by rbeer** [comment]
Looking at the recent Patreon/Paypal scandal, I actually should get rid of it entirely.
I've been too lazy to get into the BTC game, thus far. Guess it's about time. :)
