### ISSUE TITLE
QFD ban affecting notifications only

### ISSUE THREAD

**Issue by ghost** [shadowban-eu/TwitterShadowBanV2#27]
It seems like Twitter has a new type of quality filter ban that only affects notifications, not search, so this tool can't detect it. Not sure if there's a way to detect it without sending a \@mention from the user's account.

Also note that their [help page](https://help.twitter.com/en/managing-your-account/understanding-the-notifications-timeline) says this:

> Quality filter, when turned on, filters lower-quality content from your notifications, for example, duplicate Tweets or content that appears to be automated — it does not filter notifications from people you follow or accounts you’ve recently interacted with.

"Accounts you've recently intracted with" is pretty vague. A simple interaction (reply, retweet, like, or follow and then unfollow) does not seem to be enough, but for example if someone has been following you for a day you will be at least temporarily exempted from the quality filter even if they unfollow you.

**Comment by ghost** [comment]
Sorry for the bump but any idea on this?

**Comment by m-ueberall** [comment]
IMHO I came across this type of filter ban today myself: A user I don't follow replied to tweets of mine within minutes and I did not receive notifications whatsoever (neither using the new web-based UI, nor Tweetdeck, nor the Twitter API). I only saw the answers because I spotted the number of replies listed below my tweets. The thread beginning with the first answer was hidden due to the "potentially sensitive contents". Looks like the following feature is of "dual-use" type: https://www.theverge.com/2019/2/28/18245432/twitter-hide-replies-feature-test

**Comment by ghost** [comment]
That may help in detecting the QFD ban but it doesn't seem to happen consistently.

My accounts affected by QFD seem to also have a search suggestion ban most but not all of the time.

**Comment by ghost** [comment]
The reply deboosting test seems to work pretty well to detect this type of shadowban, I almost always see that test being positive on my account.

**Comment by ghost** [comment]
Here's what I've found:
* The reply deboosting test works pretty well to detect the notification QFD ban, but it's not perfect, 2 of my 7 accounts test negative for it but are definitely shadowbanned as I can't see the replies in my notifications while the quality filter is turned on.
* Search suggestion ban likely isn't actually related to this, I rarely ever see it on my account now.
* The notification filter seems to take tie strength into account just like reply deboosting, because sometimes when testing replies between my own accounts I find that I still see the notification even with the quality filter on, but when testing with friends they cannot see it.

**Comment by ghost** [comment]
I'll close this since the Reply Deboosting test works well in most cases to detect this, we probably can't really do better (apart from a test requiring user interaction perhaps).
