### ISSUE TITLE
"Something unexpected went wrong" for Ghost Ban/Reply Deboosting

### ISSUE THREAD

**Issue by ghost** [shadowban-eu/TwitterShadowBanV2#30]
![image](https://user-images.githubusercontent.com/482367/77195624-3bffe280-6ae2-11ea-86e6-d21be600194c.png)

**Comment by rbeer** [comment]
Edge case we don't account for, it seems.
https://twitter.com/SeulChae/status/725698020960964609 - the tweet this one replies to is ~deleted~ terminated: https://twitter.com/TheKpop/status/725481373490810884.
Thanks for the report!

**Comment by ghost** [comment]
Sorry, the account in question is actually `@seuichae` with an i (though the reply deboosting test does appear to fail on `@seulchae` as well).

**Comment by rbeer** [comment]
Yes, weird things are going on, though.

Viewing https://twitter.com/SeulChae/status/725698020960964609, the tweet https://twitter.com/TheKpop/status/725481373490810884 seems terminated.

If you go to another reply, it's not: https://twitter.com/VIXX_EWCT/status/725482459538722816
