### ISSUE TITLE
Resurrect link not shown on mobile

### ISSUE THREAD

**Issue by ghost** [shadowban-eu/TwitterShadowBanV2#31]
The link to "Resurrect" is not visible on mobile (Safari on iOS 13.3). It can be accessed by typing `resurrect` into the username field or visiting https://shadowban.eu/resurrect directly, but this is not very intuitive/discoverable for the average user.

**Comment by rbeer** [comment]
Weird. Do you have any means to see whether it's in the DOM, at all? Or just make a screenshot of the screen? I'm guessing it's too narrow, but then again testing with 320px in devtools still shows all 3 links.
![320px_mobile_in_dev_tools](https://user-images.githubusercontent.com/3411649/77198360-22ad6500-6ae7-11ea-84dc-b3c41272bdf4.png)

**Comment by ghost** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/482367/77198643-a6675180-6ae7-11ea-888c-212680701af7.jpeg)

**Comment by rbeer** [comment]
Thanks!
The whole header is missing? Huh...
Can you scroll up? The routing component does this weird thing where it scrolls to the top of the title.

**Comment by ghost** [comment]
Nothing here if I scroll up, it's already at the top.

![image](https://user-images.githubusercontent.com/482367/77200924-dadd0c80-6aeb-11ea-80da-05ca60c4f33f.png)

**Comment by rbeer** [comment]
god, how I hate Apple...
Ok, I'll look into it. Thanks

**Comment by rbeer** [comment]
Should be fixed now; can you confirm?
A headsup: this repo will be archived, tomorrow. New frontend - and eventually backend - will be combined in [shadowban-eu/shadowban.eu](https://github.com/shadowban-eu/shadowban.eu)

**Comment by ghost** [comment]
Yeah, it does seem to be fixed now.

**Comment by rbeer** [comment]
fixed in shadowban-eu/shadowban.eu@16022d7
