### ISSUE TITLE
Ignore self replies for reply deboosting test

### ISSUE THREAD

**Issue by pasamio** [shadowban-eu/TwitterShadowBanV2#42]
I ran the test for F1reEmpress: http://shadowban.eu/F1reEmpress

It flagged no reply deboosting, stating it could find their own reply to their own tweet:
> We found @F1reEmpress's reply to this tweet.

Reply: https://twitter.com/F1reEmpress/status/1380404336476454915
Tweet: https://twitter.com/i/status/1380404178292473856

I don't think a reply to their own tweet makes sense to hide from someone however I came to it from the OP in the thread:
https://twitter.com/Rachelanita5/status/1380399212794372100

In this thread, their reply is hidden behind a show more option.

**Comment by rbeer** [comment]
That _is_ different; they should be excluded. Good catch, thanks!

**Comment by rbeer** [comment]
Fixed in shadowban-eu/testing@21f88a6

https://next.shadowban.eu/F1reEmpress finding and correctly flagging https://twitter.com/F1reEmpress/status/1380404178292473856, i.e. the hidden gif tweet.

**Comment by pasamio** [comment]
Great! Thanks!
