### ISSUE TITLE
Search ban doesn't work

### ISSUE THREAD

**Issue by THausherr** [shadowban-eu/TwitterShadowBanV2#50]
A twitter search for "(from:DrKarlynB)" shows no results. 
https://twitter.com/search?q=(from%3ADrKarlynB)&src=typed_query
With
https://shadowban.eu/DrKarlynB , all is green.
Then I repeated the same with my account, the twitter search works.
Thus I suspect that the search shadow ban feature doesn't work properly. (Or that I discovered a new type of shadow banning?)

**Comment by rbeer** [comment]
The link in the description is wrong. It leads to the "Top" listing. We test for whether tweets show under "Latest".

https://twitter.com/search?q=from%3A%40DrKarlynB&src=typd&f=live

Twitter seems to have changed quite a bit. Nontheless, the test result is correct.

I'll keep this open, until I fixed the link. Thanks for the report! :+1:

**Comment by rbeer** [comment]
https://github.com/shadowban-eu/shadowban-eu-frontend/blob/edfd4a6034b417e9f831d9a4a6762555ed6251f5/src/js/ui/TechInfo.js#L7-L10
