### ISSUE TITLE
Results for username 111_yaron doesn't show

### ISSUE THREAD

**Issue by TalMesmo** [shadowban-eu/TwitterShadowBanV2#52]
![111_yaron](https://user-images.githubusercontent.com/82598988/126034215-d25435e2-069c-4eb7-abcc-20049594b273.png)

Hi,
testing for username 111_yaron doesn't show full results
screenshot attached.

**Comment by ghost** [comment]
It literally tells you the issue, did you try reading? It’s impossible to perform the shadowban test with no tweets. Ideally you will need a few media and reply tweets for full testing as well.

**Comment by TalMesmo** [comment]
> It literally tells you the issue, did you try reading? It’s impossible to perform the shadowban test with no tweets. Ideally you will need a few media and reply tweets for full testing as well.

I did, but I thought I remembered other users showed results without having to tweet.
Also for trying to search for a username on twitter I don't think it's mandatory to have tweets..

**Comment by ghost** [comment]
No, but if you don’t have tweets, it’s impossible to differentiate between “no results because no tweets” and “no results because shadowbanned”.

**Comment by rbeer** [comment]
We indeed pull the profile of a user to check its general status, first.

[/twitter_session.py#L187-L190](https://github.com/shadowban-eu/testing/blob/aa8f5a91bb69740896a83e5d9a0ae4c5f4b6d4d0/twitter_session.py#L187-L191)
```python
        user_id, profile = await test_profile(self, username)
        result["profile"] = profile

        if not profile["exists"] or profile.get("suspended", False) or profile.get("protected", False) or not profile.get('has_tweets'):
            return result
```

The `has_tweets` field is derived from Twitter's API response's `statuses_count`.

[/tests/profile.py#L46-L49](https://github.com/shadowban-eu/testing/blob/aa8f5a91bb69740896a83e5d9a0ae4c5f4b6d4d0/tests/profile.py#L46-L49)

```python
    try:
        profile["has_tweets"] = int(profile_raw["statuses_count"]) > 0
    except KeyError:
        profile["has_tweets"] = False
```

The "Search Suggestion" ban technically can be tested without tweets, but I remember our reasoning having been: Why would I test my account for shadowbans, if I don't tweet at all anyway? I'm open for other's needs, but from my POV there's just no practical use case for testing accounts without tweets.

**Comment by TalMesmo** [comment]
Thank you for your reply.
Well here is my reason. I hope it makes sense and gladly hear your opinion.
After getting shadowbanned and suspended many times - I decided to go slow.
Meaning that at first I created a new account, and then just "like" people at a certain rate and will increase this rate as I go.
I wanted to know what is the rate limit at which they start lowering my exposure.
Btw, the moment I tweeted something - the results were I was shadowbanned.
So I guess I was shadowbanned me before that single first tweet.

Thanks for your brilliant work - was happy to support with my small share a few weeks ago.

**Comment by rbeer** [comment]
Ok; and interesting first result. It doesn't surprise me, though:

1. My assumption is that Twitter doesn't actually delete your data when you do.That data is not only their business, but also using a `deleted` flag instead of really deleting the data is a very common practice in the industry. => allowing the premise that Twitter still has and works with your "deleted" tweets.

2.

**Comment by rbeer** [comment]
The account is new. Sorry, I missed that.
It being shadowbanned is odd then, yes. I actually can't find it in the search, so the test seems to be fine.

Maybe use the account as planned and see whether the status changes. This might just be an anomaly with new accounts; one worth documenting, nonetheless.

> Thanks for your brilliant work - was happy to support with my small share a few weeks ago.

Thank you! :+1:
