### ISSUE TITLE
Broaden reach more than just last reply tweeted

### ISSUE THREAD

**Issue by gartkb** [shadowban-eu/TwitterShadowBanV2#54]
Hi
Thanks for the valuable tool. I'm in desperate need for something that reaches more deeply, so that I can troubleshoot my own visibility though. Ideally this would comb back through all replies and give the hidden tweets text and who it was addressed to. Fine for that to be something that runs locally logged out or logged into a secondary account. I assume local execution would be necessary b/c server load would be a problem. 
thanks for your consideration!

**Comment by rbeer** [comment]
Sounds like you have something specific in mind. What exactly are you interested in? What's your usecase?
